export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const AUTH_PEDNING = "AUTH_PEDNING";

export const UPDATE_REPOSITORIES = "UPDATE_REPOSITORIES";
export const MARK_REPOSITORIES_OCCUPIED = "MARK_REPOSITORIES_OCCUPIED";
export const COLLECTION_PENDING = "COLLECTION_PENDING";
export const COLLECTION_FAILED = "COLLECTION_FAILED";

export const ADD_TO_COLLECTION = "ADD_TO_COLLECTION";
